### ISSUE TITLE
Failed Test PR #9 - Error on yarn build (Dexalot)

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/gateway#10]
## Summary and Screenshots
Getting this error when trying to execute `yarn build` using the latest commit [6e541a8](https://github.com/CoinAlpha/gateway/pull/9/commits/6e541a851aff2c93dd4f093b656e1de5abb46414).

<img width="1099" alt="Screen Shot 2023-03-16 at 11 49 00 AM" src="https://user-images.githubusercontent.com/64377055/225708740-7040779c-b8ab-4b9c-9192-0cb77f369927.png">

## Steps To Reproduce
1. Clone gateway and checkout on this branch
2. On the gateway directory run `yarn` and `yarn build` afterwards

## Test Result Comparison

<img width="684" alt="Screen Shot 2023-03-08 at 11 01 18 AM" src="https://user-images.githubusercontent.com/64377055/223793922-cad3c730-20c2-46c4-a470-a5393f773c31.png">

## Attachments
N/A

**Comment by vic-en** [comment]
@rxlxrxsx Pls confirm that issue is fixed

**Comment by rxlxrxsx** [comment]
Tested on commit [9875184](https://github.com/CoinAlpha/gateway/pull/9/commits/9875184347f6228ddb7521fca5bd7d2ecac1be04) and confirmed fixed.
