### ISSUE TITLE
Failed Test PR #11 - Cannot find module when running price and trade manual tests

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/gateway#12]
## Summary and Screenshots
Getting this error when trying to run curl test for zigzag price and trade:

<img width="1421" alt="Screen Shot 2023-03-31 at 2 04 04 PM" src="https://user-images.githubusercontent.com/64377055/229223736-535e70eb-815f-4a17-a6b2-4311855cb183.png">

## Steps To Reproduce
1. Run the client and generate gateway certs
2. Run gateway
3. Export needed variables to run curl test
4. Run curl test

## Test Result Comparison
N/A, new connector

## Attachments
N/A

**Comment by vic-en** [comment]
@rxlxrxsx This issue has been resolved in a recent commit. Thanks.

**Comment by mrhzysbl** [comment]
Tested and confirmed that there were no longer issues after pushing the commit [bf1f736](https://github.com/CoinAlpha/gateway/pull/11/commits/bf1f7367c5f7f9e2f6f6d99d412db2f536a9dd86)
