### ISSUE TITLE
Failed Test PR #11 - Error after restarting amm_arb strategy

### ISSUE THREAD

**Issue by rxlxrxsx** [CoinAlpha/gateway#14]
## Summary and Screenshots
Getting this error after restarting the amm_arb strategy. So far this issue only happens when running on cloud, tested locally but didn't get the same issue.

<img width="1423" alt="Screen Shot 2023-04-03 at 12 58 06 PM" src="https://user-images.githubusercontent.com/64377055/229601626-fa401175-a625-4f91-939b-5f25a2f31eab.png">

```python
2023-04-03 17:58:47,004 - 415408 - GatewayEVMAMM - ERROR - 'InFlightOrder' object has no attribute 'is_approval_request'
Traceback (most recent call last):
  File "/home/ubuntu/hbot-ca-dev-zigzag/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 913, in _status_polling_loop
    self.update_token_approval_status(self.approval_orders),
  File "/home/ubuntu/hbot-ca-dev-zigzag/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 166, in approval_orders
    return [
  File "/home/ubuntu/hbot-ca-dev-zigzag/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 169, in <listcomp>
    if approval_order.is_approval_request
AttributeError: 'InFlightOrder' object has no attribute 'is_approval_request'
```

## Steps To Reproduce
1. Run the client and generate gateway certs
2. Run gateway
3. Create and run an amm_arb strategy using zigzag and another connector of your choice
4. Restart the strategy (this is where the issue first happened)

## Test Result Comparison
N/A, new connector

## Attachments
[zigzag_amm.zip](https://github.com/CoinAlpha/gateway/files/11141578/zigzag_amm.zip)

**Comment by vic-en** [comment]
@rxlxrxsx The fix for this is on https://github.com/hummingbot/hummingbot/pull/6202.
Pls test with the brach in that pr.

**Comment by vic-en** [comment]
Also the give a little more context, the error initially occurred when the amm strategy is restarted when the gateway side of the strategy is sent by yet to be confirm as filled(.i.e while it still remains in the in_flight order tracker)

**Comment by mrhzysbl** [comment]
Tested and confirmed that the issue were no longer showing.
