### ISSUE TITLE
Failed Test PR #5 - Unable to install gateway using yarn

### ISSUE THREAD

**Issue by mrhzysbl** [CoinAlpha/gateway#6]
## Summary and Screenshots
Able to clone the repo successfully but after running the yarn command, an error message shows "fatal: Could not read from remote repository." 

<img width="700" alt="Screen Shot 2023-02-24 at 7 47 04 PM" src="https://user-images.githubusercontent.com/120451804/221176102-1ce336ba-fc2b-4a9c-b987-6f58e9ed9bd9.png">

## Steps To Reproduce
1. Clone repo: git clone -b feat/xdc_chain_and_xdcswap https://github.com/CoinAlpha/hummingbot.git
2. Run the command yarn

## Test Result Comparison
Dev branch: 
<img width="719" alt="Screen Shot 2023-02-24 at 8 37 10 PM" src="https://user-images.githubusercontent.com/120451804/221180772-c84c5212-0fd4-4833-bee6-4712138e5c1d.png">

**Comment by rxlxrxsx** [comment]
- This is confirmed working on my end using node version `18.0.0`.

<img width="1421" alt="Screen Shot 2023-02-24 at 7 01 02 AM" src="https://user-images.githubusercontent.com/64377055/221205002-f0e09922-2734-451d-b678-474b687fd449.png">

<img width="681" alt="Screen Shot 2023-02-24 at 7 03 08 AM" src="https://user-images.githubusercontent.com/64377055/221205032-cce3dec2-7956-4a1f-b1a8-a1b39c4fad2b.png">

<img width="853" alt="Screen Shot 2023-02-24 at 7 03 58 AM" src="https://user-images.githubusercontent.com/64377055/221205141-7c7abe04-180b-479d-9676-b770184ed572.png">

- Can you try using the same version as mine? Also make sure you run the `yarn` command on the gateway repo and not on the the hummingbot client repo.
